[package]
name = "kvnc-dag"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kvnc-types = { path = "../kvnc-types" }
kvnc-storage = { path = "../kvnc-storage" }
kvnc-crypto = { path = "../kvnc-crypto" }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
redb = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
