[package]
name = "kvnc-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kvnc-types = { path = "../kvnc-types" }
ed25519-dalek = { workspace = true }
blake3 = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
