[package]
name = "kvnc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kvnc"
path = "src/main.rs"

[dependencies]
kvnc-types = { path = "../kvnc-types" }
kvnc-crypto = { path = "../kvnc-crypto" }
kvnc-common = { path = "../kvnc-common" }
kvnc-htlc = { path = "../kvnc-htlc" }
kvnc-vault = { path = "../kvnc-vault" }
kvnc-multisig = { path = "../kvnc-multisig" }
kvnc-token = { path = "../kvnc-token" }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
argon2 = "0.6"
bip39 = { version = "3", features = ["zeroize"] }
chacha20poly1305 = "0.10"
rand = { workspace = true }
rpassword = "7.5"
tempfile = "3"
zeroize = "1"
